# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e58aa67ed000bb876f916950b3961d3b91378e03f754d2ecbf629ac38fe880ca7ccb5f380fed4b395abd15cca9b8cf31c7428fbd77b8b8f4f89e868f7401723c

test:
  secret_key_base: 29e9ff5a342c25a19659dab897bffa2d995567b6cdb88a606106b69a799029dcdfe9369e29356ec4f627125b55ba37a26e7651a585923ddf5b23a44c4126a09d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
